DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS recipe CASCADE;
DROP TABLE IF EXISTS ingredient CASCADE;
DROP TABLE IF EXISTS recipe_ingredient CASCADE;
DROP TABLE IF EXISTS followed_recipe CASCADE;
DROP TABLE IF EXISTS user_ingredient_score CASCADE;
DROP TABLE IF EXISTS meal_plan CASCADE;
